SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS OUTS
         LEFT JOIN ANIMAL_INS INS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.ANIMAL_ID IS NOT NULL
ORDER BY TIMESTAMPDIFF(DAY, INS.DATETIME, OUTS.DATETIME) DESC
LIMIT 2;

SELECT HOUR(OUTS.DATETIME), COUNT(*) AS count
FROM ANIMAL_OUTS OUTS
WHERE HOUR(OUTS.DATETIME) > 8 AND HOUR(OUTS.DATETIME) < 20
GROUP BY HOUR(OUTS.DATETIME)
ORDER BY HOUR(OUTS.DATETIME);